name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Run tests
      run: go test -v ./...
    - name: Build kubectl-tbac Linux binary
      run: go build -o dist/linux/amd64/kubectl-tbac
      env:
          GOOS: linux
          GOARCH: amd64
    - name: Build kubectl-tbac Mac binary
      run: go build -o dist/darwin/amd64/kubectl-tbac
      env:
        GOOS: darwin
        GOARCH: amd64
    - name: Build kubectl-tbac Windows binary
      run: go build -o dist/windows/amd64/kubectl-tbac.exe
      env:
        GOOS: windows
        GOARCH: amd64
    - name: Upload kubectl-tbac Linux binary
      uses: actions/upload-artifact@v1
      with:
        name: kubectl-tbac-linux
        path: dist/linux/amd64/kubectl-tbac
    - name: Upload kubectl-tbac Mac OS binary
      uses: actions/upload-artifact@v1
      with:
        name: kubectl-tbac-macos
        path: dist/darwin/amd64/kubectl-tbac
    - name: Upload kubectl-tbac Windows binary
      uses: actions/upload-artifact@v1
      with:
        name: kubectl-tbac-windows
        path: dist/windows/amd64/kubectl-tbac.exe